### ISSUE TITLE
Influx Cmd Batching is not thread safe

### ISSUE THREAD

**Issue by ssailer** [unc-enap/Orca#98]
https://github.com/unc-enap/Orca/blob/77e5a3edc1545d065a83232b713ca5893c32e71a/Source/Objects/Misc%20Objects/InFluxDB/ORInFluxDBModel.m#L485

The enum for loop might throw exceptions for high rates of measurements.

**Comment by jfwilk** [comment]
Hi Simon, is this problem now fixed?

**Comment by ssailer** [comment]
Yes this has been fixed with PR#99, closing.
